# Generated by Django 3.2.9 on 2021-11-29 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(max_length=50, verbose_name='Date de naissance')),
                ('address', models.CharField(max_length=100, verbose_name='Lieu de residence')),
                ('formation', models.CharField(max_length=15, verbose_name='Formation')),
                ('phone', models.CharField(max_length=10, verbose_name='Contact')),
                ('startdate', models.DateField(max_length=200, verbose_name='Date entrée')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date du jour')),
                ('arrivee', models.TimeField(auto_now=True, null=True, verbose_name="Heure d'arrivée")),
                ('depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('temps', models.TimeField(blank=True, null=True, verbose_name='Temps de travail')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apprenant')),
            ],
        ),
    ]
